### ISSUE TITLE
Thats amazing!!

### ISSUE THREAD

**Issue by J053Fabi0** [raydog/github-drawing#1]
Great job my friend

**Comment by J053Fabi0** [comment]
What GitHub drawer do you use?

**Comment by raydog** [comment]
@J053Fabi0 Sorry for the slow reply. This repo is actually its own custom github drawer. See generate.go, specifically:

- `newPatternFromFile()` to load the pattern from the "image.txt" file.
- `(*Pattern) Draw()` to "draw" that pattern using forged empty commits.
- `forgeCommit` for the actual forging logic, that fakes a commit date, and makes an empty commit.
